hydra:
  job:
    chdir: true 

  run:
    dir: /Users/omer/Desktop/InstaDeep/DL_use_case/
  sweep:
    dir: /Users/omer/Desktop/InstaDeep/DL_use_case/
  output_subdir: null # Disable automatic addition of subfolders based on date/time

model:
  hidden_layers: [16, 16, 16]  # MLP hidden layers

training:
  learning_rate: 0.001
  epochs: 100_000

prop:
  b: 0.3
  m: 1.0
  l: 1.0
  g: 9.81

solver:
  t_start: 0
  t_end: 20
  dt: 0.01

plot:
  save_dir: ./plots